name: CI/CD Pipeline with Email Verification

# Triggers the workflow on push to the main branch
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checks out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: The required step with the email address as the name
      # This step simply runs a shell command to confirm the environment is working.
      - name: 22ds3000113@ds.study.iitm.ac.in
        run: |
          echo "Hello, world!"
          
      # Step 3: Example step for setting up Python dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 4: Example step for testing (replace with your actual commands)
      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          # Replace 'pytest' with your actual test command
          echo "Running unit tests..."
          # pytest 
          echo "Tests passed successfully."
